---
title: "Harvard Enrollment in Language Courses"
author: "Ruoqi Zhang"
date: "4/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, warning = FALSE)
library(tidyverse)
library(gt)
library(readxl)
library(janitor)
library(fs)
library(purrr)
library(stringr)
library(ggrepel)
```

```{r data_fetch, results='hide'}

# Fetches Enrollment Data and Transform Into Tibble
#
# This function takes in two strings and creates tibble objects accordingly. It
# is intended to take in Harvard Registrar's enrollment records and turn them
# into corresponding tibbles.
#
# @param table_url A string. The url of enrollment files provided by Harvard
#   Registrar.
# @param term A string. Used to describe the semester of the enrollment file.
#   Will also name the object created for the tibble.
# @return A tibble named by parameter term, containing data from table_url.

file_to_df <- function(table_url, term) {
  
  # Filters Courses That Are Language Courses
  # 
  # A function to process dataframes from different semesters. It cleans variable
  # names, and filters out the courses that are language courses It also
  # filters out rows that are not courses.
  # 
  # @param enrollment_df A dplyr tibble.
  # @return A cleaned dplyr tibble with courses that are language courses
  
  filter_languages <- function(enrollment_df) {
    enrollment_df %>% 
      clean_names() %>% 
      filter(!is.na(course_title),
             
             # We choose these languages because they are the six official
             # languages in the United Nations.
             
             str_detect(course_title, "ARABIC") | str_detect(course_title, "CHNSE") | str_detect(course_title, "SPANSH") | str_detect(course_title, "RUSS") | str_detect(course_title, "FRENCH") | str_detect(course_title, "SPANSH"))
  }

  # We don't want all the downloaded files to be piled in the working directory.
  # Therefore, we create a directory to store the downloaded excel files. We
  # first examine whether the directory already exists. If not, we create a
  # directory called enrollment_data/ under the working directory.
  
  if (!dir.exists(file.path(getwd(), "enrollment_data"))) {
    dir.create(file.path(getwd(), "enrollment_data"))
  }
  
  # This variable is used for the destfile parameter for download.file. 
  
  file_destination = paste0("enrollment_data/", term, ".xlsx")
  
  # Download the enrollment data provided by Harvard Registrar.
  
  download.file(url = table_url, destfile = file_destination, mode = "wb")
  
  # The enrollment data for Fall 2018 is stored differently than other years'.
  # We treat them differently (skip different number of lines) by using
  # conditional statement.

  # For each semester, we want an individual tibble to store its data.
  # Therefore, to dynamically name variables, we use the assign() function to
  # assign the data to the name specified by parameter 'term'. To make the
  # objects accessible outside the function body, we specify parameter envir as
  # .GlobalEnv, thus making it accessible in the entire environment.
  
  if (term == "fall_2018") {
    assign(term, read_excel(file_destination, skip = 2) %>% filter_languages(), envir = .GlobalEnv)
  } else {
    assign(term, read_excel(file_destination, skip = 3) %>% filter_languages(), envir = .GlobalEnv)
  }
}

# FAS reports its enrollment data in a consistent manner after 2016-17 school
# year. We manually specify all the terms after that.

terms <- c("spring_2019", "fall_2018", "spring_2018", 
           "fall_2017", "spring_2017", "fall_2016")

# We specify the link to enrollment data that corresponds to the term specified
# in variable 'terms'.

sheet_urls <- c("https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19.xlsx",
                 "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_10.24.18.xlsx",
                 "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_03.06.18.xlsx",
                 "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_10.20.17.xlsx",
                 "http://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2017_03_07_final_0.xlsx",
                 "http://registrar.fas.harvard.edu/files/fas-registrar/files/copy_of_class_enrollment_summary_by_term_10.06.2016.xlsx")

# Using map2() from purrr, we run file_to_df once for every term-url
# combination, thus generating a tibble for every semester's data.

map2(sheet_urls, terms, file_to_df)


```

```{r graph_creation, fig.height=5, fig.width=8, fig.align='center'}

# Calculate the number of enrollees for each language in a term
#
# This function takes in the string description of a term and calls the
# corresponding tibble containing the term's enrollment data. It then returns a
# tibble that contains the number of enrollees for each language.
#
# @param term A string specifying the semester
# @return A dplyr dataframe that contains the number of enrollees for each
#   language in the specified term.

sum_language <- function(term) {
  
  # We use a string input to specify the term because in the previous code, we
  # already had a list that contains the terms that we are interested in. To
  # call the corresponding tibble, we treat string object 'term' as a name, and
  # evaluate it. This, in effect, would call the tibble that contains the
  # enrollment data for that term.
  
  eval(as.name(term)) %>% 
    
    # We are interested in the total enrollee in a specific language, regardless
    # of levels. We observe the course_title variable, and found that each
    # langugae has its unique course code + difficulty level (e.g. CHNSE Bb).
    # Therefore, we create a new variable that contains the first component
    # (e.g. CHNSE) of the course_title to describe the language of the course.
    
    mutate(course_language = str_split_fixed(course_title, " ", 2)[,1]) %>% 
    
    # For each language, count the total enrollees.
    
    group_by(course_language) %>% 
    summarize(num_enrollee = sum(total))
}

# We join the tibbles across years together by using full_join. Here, the suffix
# are formatted to ensure convenience. The suffix's first 4 digits represent the
# year of the semester, and the ensuing two letters represent the term (01
# stands for Spring, 02 stands for Fall.)

sum_language("fall_2016") %>%
  full_join(sum_language("spring_2017"), by = "course_language", 
            suffix = c(".201602", ".201701")) %>% 
  full_join(sum_language("fall_2017"), by = "course_language", 
            suffix = c(".201701", ".201702")) %>% 
  full_join(sum_language("spring_2018"), by = "course_language", 
            suffix = c(".201702", ".201801")) %>% 
  full_join(sum_language("fall_2018"), by = "course_language", 
            suffix = c(".201801", ".201802")) %>% 
  full_join(sum_language("spring_2019"), by = "course_language", 
            suffix = c(".201802", ".201901")) %>% 
  
  # We replace all NA values as 0.
  
  replace(is.na(.), 0) %>% 
  
  # To create ggplot graph, we need to gather all the columns. We first use
  # gather function to achieve this, naming the term variable as 'term' and the
  # number of enrollee as 'num_enrollee'.
  
  gather(key = "term", value = "num_enrollee", num_enrollee.201602:num_enrollee.201901) %>% 
  
  # This, however, creates a problem because the strings in 'term' variable are
  # in the format of num_enrollee.yearterm. We only need the descriptor for the
  # year and the term, and do not need the num_enrollee suffix because it's
  # already specified by the variable name. Therefore, we split the string and
  # take the latter part describing the year and term of a row.
  
  mutate(term = str_split_fixed(term, "enrollee.", 2)[,2]) %>% 
  
  # We refactor the 'term' variable, and specifies labels for each term for
  # display in the plot.
  
  mutate(term = factor(term, levels = c("201602", "201701", "201702", "201801", "201802", "201901"),
                       labels = c("Fall 2016", "Spring 2017", "Fall 2017", "Spring 2018", 
                                  "Fall 2018", "Spring 2019")),
         
         # Refactor the 'course_language' variable to display a more
         # human-readable name in the plot.
         
         course_language = factor(course_language, levels = c("ARABIC", "CHNSE", "FRENCH", "RUSS", "SPANSH"),
                                  labels = c("Arabic", "Chinese", "French", "Russian", "Spanish"))) -> languages_df

# Filter the language enrollment tibble to get, for each language, the term
# during which that language has the largest enrollment.

top_enrollment_term <- languages_df %>% 
  group_by(course_language) %>% 
  
  # Use top_n function to get the entire row for each group's row with the
  # largest num_enrollee.
  
  top_n(n = 1, wt = num_enrollee)

languages_df %>% 
  ggplot(aes(x = term, y = num_enrollee, color = course_language, group = course_language)) +
  
    # I am using geom_point and geom_line at the same time because I think
    # visually this would better demonstrate the breaks in those lines,
    # emphasizing the enrollment data is based on terms.
  
    geom_point(size = 1) +
    geom_line() +
  
    # We use geom_text_repel in the ggrepel package to label the term that has
    # the largest enrollment number for each language. We set parse as TRUE so
    # that it will evaluate the statement in the label parameter. A caveat is
    # that geom_text_repel does not avoid geom_line, therefore, we used size,
    # nudge_x/y to further adjust the labels position, so that they do not
    # overlap with the lines.
  
    geom_text_repel(data = top_enrollment_term, 
                    mapping = aes(x = term, y = num_enrollee, 
                                  label = paste(course_language, num_enrollee, sep = ": ")),
                    show.legend = FALSE, parse = TRUE, size = 3, nudge_x = -0.1, nudge_y = -60) +
  
    # I like theme_minimal()
  
    theme_minimal() +
    labs(x = NULL,
         y = "Total Enrollees",
         color = "Language",
         title = "Enrollment in Language Courses at Harvard University",
         subtitle = "For U.N. Official Languages (excl. English)",
         caption = "Numbers on the plot represent the number of enrollee in the year of the languages' highest \n\nIncludes enrollments from undergraduates, visiting undergraduates,\nnon-degree students, employees, and other students.\n\nSource: Harvard Registrar") +
    scale_y_continuous(breaks = c(0, 200, 400, 600)) +
  
    # We want the y axis to start at 0 to create an accurate impression for the
    # enrollment situation for Russian.
  
    expand_limits(y = 0) +
  
    # We use scale_color_brewer to specify a color scheme.
  
    scale_color_brewer(palette = "Dark2") -> enrollment_plot

# Save the graph to graphs/ directory. Here, we use the dir_create function in fs package, which will create a directory if there is no existing one. Then, we use ggsave to save the plot.

dir_create("graphs/")
ggsave("graphs/language-enrollment.png", enrollment_plot, width = 8, height = 5)

# Display the plot.

enrollment_plot

```

